version: "3.9"

services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=webbudget
      - POSTGRES_USER=sa_webbudget
      - POSTGRES_PASSWORD=sa_webbudget
    networks:
      - wb-network

  backend:
    image: arthurgregorio/webbudget-backend:latest
    ports:
      - "8085:8085"
    environment:
      - DATABASE_URL=database:5432
      - MAIL_HOST=host
      - MAIL_USER=user
      - MAIL_PASSWORD=password
    depends_on:
      - database
    networks:
      - wb-network

  frontend:
    image: arthurgregorio/webbudget-frontend:latest
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:8085
    depends_on:
      - backend
    networks:
      - wb-network

networks:
  wb-network:
    name: wb-network
